pkg/controllers/util/clusterutil.go, test/e2e/framework/framework.go
There is a bug with the `FederatedInformer` when using the insecure option for federated clusters. It calls `BuildClusterConfigWithGenericClient` which incorrectly leaves out the TLS certs when the insecure option is set. This causes the FederatedInformer's listwatch to fail, affecting controllers that still use the `FederatedInformer`.
=> Fix: handling of insecure clusters in FederatedInformer

CONTRIBUTING.md, docs/code-style.md
We currently do not have any logging conventions, resulting in noisy and inconsistent logs across different controllers. I would like to propose the following logging conventions outlined in the newly added code style guide.
Afterwards, we will have to refactor the existing code to follow this new logging convention, which I will open a new issue for.
=> Introduce logging conventions

config/crds/core.kubeadmiral.io_clusterpropagationpolicies.yaml, config/crds/core.kubeadmiral.io_propagationpolicies.yaml, config/crds/patches/core.kubeadmiral.io_clusterpropagationpolicies.sh, config/crds/patches/core.kubeadmiral.io_clusterpropagationpolicies.yaml, config/crds/patches/core.kubeadmiral.io_propagationpolicies.sh, config/crds/patches/generic_propagationpolicies.src.sh, hack/generate-groups.sh
Label values cannot exceed 63, so pp/cpp names that are too long cannot work anyway
=> fix: limit pp/cpp length to 63

test/e2e/framework/resources/resources.go, test/e2e/framework/util/util.go, test/e2e/resourcepropagation/cronjobs.go, test/e2e/resourcepropagation/deployments.go, test/e2e/resourcepropagation/framework.go, test/e2e/resourcepropagation/jobs.go
Refactor the existing resource propagation tests using a generic (using golang generics) framework, allowing the easy addition of e2e tests for new types of resources while preventing code duplication.
=> test(e2e): implement generic resource propagation framework

docs/code-style.md
There were some ambiguities in the logging conventions, that made it difficult to distinguish when to use log levels 2, 3 and 4 respectively. 
This PR refines the descriptions of each log level so that it is clearer when each level should be applied.
An additional rule is added for logging before actions in the present continuous tense.
=> Doc: refine logging conventions

cmd/controller-manager/app/util.go, pkg/controllers/federatedcluster/clusterstatus.go, pkg/controllers/federatedcluster/util.go, test/e2e/framework/cluster/cluster.go
When api discovery for a member cluster fails, the cluster controller errors out and does not set the ready and offline conditions on the `FederatedCluster`. This PR updates the status update logic to also set ready and offline conditions (with new reasons explaining the issue) when api discovery or resource collection for a cluster fails.
This PR also fixes a regression where cluster join timeout defaults to 0 seconds, and makes cluster condition matching in e2e tests more stringent.
=> fix(cluster): add ready condition when api discovery fails

.golangci.yml, cmd/controller-manager/app/core.go, examples/scheduler/webhook/main.go, pkg/controllers/scheduler/constants.go, pkg/controllers/scheduler/core/generic_scheduler.go, pkg/controllers/scheduler/core/generic_scheduler_test.go, pkg/controllers/scheduler/extensions/webhook/v1alpha1/plugin.go, pkg/controllers/scheduler/extensions/webhook/v1alpha1/plugin_test.go, pkg/controllers/scheduler/profile.go, pkg/controllers/scheduler/scheduler.go, pkg/controllers/scheduler/scheduler_test.go, pkg/controllers/scheduler/schedulingunit.go, pkg/controllers/scheduler/webhook.go, pkg/controllers/scheduler/webhook_test.go, test/e2e/automigration/automigration.go
Notable changes:
Features:
- Allow webhook plugins to be referenced and used by `SchedulerProfile` (with integration tests)
- webhook plugins now handle non-200 responses correctly (with unit tests)
Fixes:
- extract workload template correctly when creating scheduling unit (with unit tests)
Refactors:
- split scheduler's `reconcile` function into smaller functions
- standardise logging in `generic_scheduler.go`
- scheduling `Algorithm` no longer holds a reference to cluster store; clusters are passed explicitly into `Schedule`
Docs:
- Add sample scheduler webhook
=> Webhook plugin integration

cmd/controller-manager/app/options/options.go, cmd/controller-manager/app/util.go, go.mod, go.sum, pkg/controllers/util/federatedclient/client.go, pkg/controllers/util/federatedclient/podinformer.go, pkg/controllers/util/federatedclient/podinformer_test.go
Use a custom Pod Informer to limit the number of concurrent list pods from member clusters, and simplify the metadata of the pods before we store them into the cache.
The reference conversations: https://github.com/kubewharf/kubeadmiral/pull/14
As result:
4 clusters, 100 kwok-node/cluster, 10 deployment/cluster, 1000 pod/deployment, total: 10k pod/cluster
* case1: simplify the pod (In the last three rounds, kwok failed to delete pods of a cluster so the pods of cluster came to 20k; and some kwok nodes got not ready, so the available cpu,gpu came to zero, but the pods still in work. The overall impact is not significant.)
* case2: regular pod informer
* case3: simplify the pod and limit 2 available listers 
* case4: simplify the pod, ignore modified event of watch, and limit 2 available …
=> feat: customize pod informer to reduce memory usage

config/crds/core.kubeadmiral.io_federatedclusters.yaml, pkg/apis/core/v1alpha1/types_federatedcluster.go, pkg/apis/core/v1alpha1/zz_generated.deepcopy.go, pkg/controllers/federatedcluster/clusterjoin.go, pkg/controllers/federatedcluster/clusterstatus.go, pkg/controllers/federatedcluster/controller.go, pkg/controllers/federatedcluster/util.go, test/e2e/e2e_test.go, test/e2e/federatedcluster/clusterjoin.go, test/e2e/framework/cluster/cluster.go
Main contribution:
* Cluster that failed to join due to reachability issues will not be blocked for clean-up upon deletion
This is achieved by recording whether any effectual action was performed during joining in a new status field `JoinPerformed`. Upon deletion, we only require clean-up if `JoinPerformed` is true.
Note: a cluster that failed to join but underwent partial joining process (e.g. namespace created but rbac not created) will still require clean-up.
Other contributions:
* Refactor `FederatedCluster` API types:
* secretRef is no longer required
* lastTransitionTimestamp, reason, message in conditions are now value types and required
* disallow conditions with duplicate types
* make conditions optional
* reword message and reason description
* Standardise contextual logging in …
=> fix: removal of unjoined cluster should not hang

cmd/controller-manager/main.go, pkg/controllers/federate/controller.go, pkg/controllers/status/controller.go, pkg/controllers/util/clusterutil.go, pkg/controllers/util/genericinformer.go, pkg/controllers/util/worker/constants.go, pkg/util/signals/signal.go, test/e2e/framework/resources/resources.go
This pr stops the federate controller from retrying after an `Invalid` error is returned on creation. This is because the federated object template will continue to be invalid until there is an update to the source object. Thus, there is no point in retrying after receiving this error.
In addition:
1. Signal handler is refactored for clarity and to avoid the use of a global channel
2. Log level is increased for some unimportant logs
3. `pullIfNotPresent` policy is used for e2e container images to speed up tests
=> fix: federating invalid templates

pkg/controllers/common/constants.go, pkg/controllers/federate/util.go, pkg/controllers/sync/dispatch/retain.go, pkg/controllers/sync/dispatch/retain_test.go, pkg/controllers/sync/resource.go
- don't sync labels like `kubeadmiral.io/propagation-policy-name` to members
- merge desired and observed labels during update to allow controllers in member clusters to manipulate labels
- propagate deletion of labels/annotation from template to members
=> feat(retain): enhance label propagation

pkg/controllers/automigration/controller.go, pkg/controllers/federatedtypeconfig/federatedtypeconfig_controller.go, pkg/controllers/status/controller.go, pkg/controllers/statusaggregator/controller.go, pkg/controllers/sync/controller.go, pkg/controllers/util/federatedinformer.go
With this PR, the following controllers will no longer block when a single cluster's cache is not synced:
* Sync
* Status
* StatusAggregator
* AutoMigration
This is done by sending a direct request to the member API server before the caches are synced.
=> fix: cluster cache sync blocks reconcile

config/sample/host/01-ftc.yaml
As `Divide` scheduling mode is not supported for statefuleset, `pathDefinition` field should be removed in ftc
=> remove pathDefinition in ftc for statefulset

pkg/apis/types/v1alpha1/types_status.go, pkg/controllers/federatedtypeconfig/crd_schema.go, pkg/controllers/federatedtypeconfig/federatedtypeconfig_controller.go, pkg/controllers/sync/controller.go, pkg/controllers/sync/dispatch/managed.go, pkg/controllers/sync/history.go, pkg/controllers/sync/status/status.go, pkg/controllers/util/annotation/annotation.go, pkg/controllers/util/managedlabel.go, pkg/controllers/util/resourceinformer.go
Main contribution:
- add `syncedGeneration` field in federated object
- rename variables with `KubeFed` to `KubeAdmiral`
After this pr merged, users can see the syncedGeneration in federated object status:
```
status:
clusters:
- generation: 1
name: kubeadmiral-member-1
status: OK
- generation: 1
name: kubeadmiral-member-2
status: OK
- generation: 1
name: kubeadmiral-member-3
status: OK
conditions:
- lastTransitionTime: "2023-05-30T12:36:20Z"
lastUpdateTime: "2023-05-30T12:36:20Z"
status: "True"
type: Propagation
syncedGeneration: 10
```
=> add syncedGeneration field in federated object

Makefile, docs/quickstart.md, hack/dockerfiles/Dockerfile, hack/lib/deploy-kubeadmiral.sh, hack/lib/util.sh, hack/make-rules/build-images.sh, hack/make-rules/clean-local-cluster.sh, hack/make-rules/deploy-kubeadmiral.sh, hack/make-rules/local-up.sh
1. Update the content about cluster installation in quickstart;
2. Starting the kubeadmiral cluster will no longer directly modify the files in the repository;
3. Split the kubeconfig of kubeadmiral-host and kubeadmiral-meta into two to reduce the cost of using local kubeadmiral for users.
If everything went well in the installation steps, we will see the following messages:
```
Your local KubeAdmiral has been deployed successfully!
To start using your KubeAdmiral, run:
export KUBECONFIG=$HOME/.kube/kubeadmiral/kubeadmiral.config
To observe the status of KubeAdmiral control-plane components, run:
export KUBECONFIG=$HOME/.kube/kubeadmiral/meta.config
To manage your member clusters, run:
export KUBECONFIG=$HOME/.kube/members.config
Please use 'kubectl config use-context …
```
=> docs: update the content about cluster installation in quickstart

pkg/controllers/common/constants.go, pkg/controllers/federate/util.go
Main contribution:
- record the merge patch document for source object in the annotations of federated object 
the annotation is shown as below:
```kubeadmiral.io/template-generator-merge-patch: '{"metadata":{"annotations":{"kubeadmiral.io/latest-replicaset-digests":null,"kubeadmiral.io/scheduling":null,"kubeadmiral.io/status":null,"kubeadmiral.io/syncing":null},"creationTimestamp":null,"finalizers":null,"generation":null,"labels":{"kubeadmiral.io/propagation-policy-name":null},"managedFields":null,"resourceVersion":null,"uid":null},"status":null}'```
=> record the pruning merge patches for source object in the annotations of federated object

pkg/controllers/sync/controller.go, pkg/controllers/sync/dispatch/checkunmanaged.go, pkg/controllers/sync/dispatch/managed.go, pkg/controllers/sync/dispatch/unmanaged.go, pkg/controllers/sync/resource.go, pkg/controllers/util/federatedinformer.go, pkg/controllers/util/managedlabel/managedlabel.go, pkg/controllers/util/resourceinformer.go
`GetClusterObject` has a bug where if it defaults to getting directly from the cluster, it may return unmanaged objects. This causes the sync, status and status aggregation controllers to not work correctly.
Additional changes:
* functions dealing with managed label is now moved to a new package
* additionally handle `NoMatch` error (return nil when requested object's GVK is not found)
=> fix: GetClusterObject should return only managed objects

pkg/controllers/statusaggregator/controller.go, pkg/controllers/statusaggregator/plugins/job.go, pkg/controllers/statusaggregator/plugins/job_test.go, pkg/controllers/statusaggregator/plugins/plugin.go, pkg/controllers/statusaggregator/plugins/pod.go, pkg/controllers/statusaggregator/plugins/pod_test.go
When the FTC of the pod and job enables `statusAggregation`, now we can get the aggregated status of job and pod on the native resources on the federation side.
For pods, InitContainerStatuses and ContainerStatuses are collected. The aggregated startTime depends on the earliest startTime in the member cluster pod, and the aggregated pod phase is generated by the following priorities:
1. If there is any failed pod, the aggregation phase is `Failed`
2. If there is any pending pod, or a pod whose status is empty, the aggregation phase is `Pending`
3. If there is any running pod, the aggregation phase is `Running`
4. If **all** pods are succeeded, the aggregation phase is `Succeeded`
For jobs, the sum of all Active, Succeeded and Failed pods will be collected. The aggregated startTime depends …
=> feat: add status aggregator plugins for job and pod

.github/workflows/ci.yml
Mainly to catch using `ginkgo.Eventually` without assertion.
=> ci: bump golangci-lint to 1.53.3

pkg/controllers/util/annotation/annotation.go, pkg/controllers/util/annotation/annotation_test.go, pkg/controllers/util/sourcefeedback/util.go
=> fix: use metav1.Object instead of runtime.Object for more ergonomic annotation handling

pkg/util/informermanager/informermanager.go, pkg/util/informermanager/informermanager_test.go, pkg/util/informermanager/interface.go
This PR adds FTC update handlers that are called every time the `InformerManager` processes an FTC. The purpose of this is to allow controllers to hook into the `InformerManager`'s view of a FTC's lifecycle. For example, reenqueue all FOs and CFOs for a FTC when it is created or when its configuration changes.
In addition, `InformerManager.HasSynced` is also modified to only return `true` when an initial snapshot of FTCs is processed. This allows controllers to avoid false "lister not found" or "ftc not found" on controller-manager startup where it processes FOs or CFOs before their corresponding FTCs are processed by `InformerManager`.
=> feat: informer manager ftc update handlers

pkg/controllers/common/constants.go, pkg/controllers/federate/util.go, pkg/controllers/follower/controller.go
We may encounter scalability problems if a follower resource (e.g.: confimap) is automatically mounted on all deployments. This could result in too much information about the leader-follower relationship being kept on the follower resource.
If the follower resource is annotated with `kubeadmiral.io/disable-following="true"`, the resource will not follow any leader resources for scheduling.
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
annotations:
kubeadmiral.io/disable-following: "true"
name: echo-server
namespace: default
data: {}
```
=> feat: add `kubeadmiral.io/disable-following` annotation to control the scheduling behavior of follower resources.

cmd/controller-manager/app/util.go, pkg/util/informermanager/federatedinformermanager.go, pkg/util/informermanager/federatedinformermanager_test.go, pkg/util/informermanager/informermanager.go, pkg/util/informermanager/interface.go, pkg/util/informermanager/podinformer.go
This PR integartes the old custom pod informer in `FederatedClient` into `FederatedInformerManager`. This is in preparation for the FederatedCluster controller refactor. 
Additionally, `FederatedInformerManager` now also waits for an initial snapshot of clusters to be reconciled and their respective `InformerManagers` to be synced before returning true in its own `HasSynced` method. This reduces the amount of false errors on start-up where host `InformerManager`'s view of FTCs is out of sync with the member `InformerManagers`' view.
=> feat: integrate pod informer to federated informer manager

pkg/controllers/federatedcluster/clusterstatus.go, pkg/controllers/federatedcluster/controller.go
Record the cluster health check body when federated cluster is not ready, so we can analyze the cause of the anomaly.
=> chore:add log when federated cluster is not ready

Makefile, config/deploy/controlplane/kubeadmiral-controller-manager.yaml
Since kubeadmiral-controller-manager no longer needs to the flag `--create-crds-for-ftcs`, we need to delete the flag in the deploy yaml.
=> fix: kubeadmiral-controller-manager crash when make local-up

pkg/controllers/scheduler/schedulingunit.go
Fix bugs in `getCurrentReplicasFromObject` function of Scheduler:
- The wrong field is selected when validating replicasPath
- If the `json.Unmarshal` function receives nil, it will return an InvalidUnmarshalError
=> fix(scheduler): unable to get current replicas from federatedObject correctly

pkg/controllers/statusaggregator/controller.go
Ignore the not found err which will block status aggregation. And delay the fedObj triggers, cause that it depends on sync-controller to sync cluster objs.
=> fix(status-aggregator): ignore notfound err

pkg/apis/core/v1alpha1/extensions_schedulingprofile.go, pkg/controllers/scheduler/framework/plugins/clusterready/clusterready.go, pkg/controllers/scheduler/framework/plugins/names/names.go, pkg/controllers/scheduler/profile.go
This PR adds a filter plugin that will prevent scheduling onto unready clusters, unless the resource was already previously scheduled to the cluster.
=> feat(scheduler): unready cluster filter

pkg/apis/core/v1alpha1/types_federatedobject.go, pkg/controllers/automigration/controller.go, pkg/controllers/federatedcluster/clusterstatus.go, pkg/controllers/statusaggregator/controller.go, pkg/controllers/sync/controller.go
Add PendingCreate status at first when sync controller works on new selected clusters. So we only need to check objects in these member clusters when we need to delete them.
=> fix: deletion was blocked when other clusters are not ready

pkg/controllers/follower/controller.go, pkg/controllers/sync/controller.go, pkg/controllers/sync/dispatch/managed.go, pkg/controllers/sync/dispatch/unmanaged.go
- Add some metrics for the `follower controller`, test results:
```shell
kubeadmiral_controller_manager_followers_total{name="echo-server-deployments.apps",namespace="default",resource="Deployment.apps"} 1
....
kubeadmiral_controller_manager_leaders_total{name="echo-server-configmaps",namespace="default",resource="ConfigMap"} 1
...
```
- Add some metrics for the `sync controller`, test results:
```shell
kubeadmiral_controller_manager_workload_sync_error_total{cluster="kubeadmiral-member-2",error_type="UpdateFailed",name="echo-server",namespace="default",operation="update",resource="apps/v1, Kind=Deployment"} 4
...
kubeadmiral_controller_manager_workload_sync_duration_seconds_seconds{cluster="kubeadmiral-member-1",name="echo-server",namespace="default",operation="create",resource="/v1, …
```
=> feat(metric): add some metrics for follower and sync controller

pkg/controllers/federatedcluster/clusterjoin.go, pkg/controllers/federatedcluster/clusterstatus.go, pkg/controllers/federatedcluster/controller.go, pkg/util/cluster/util.go
Add cluster metrics.
Test results:
```
kubeadmiral_controller_manager_cluster_cpu_allocatable_number{cluster_name="kubeadmiral-member-1"} 4
kubeadmiral_controller_manager_cluster_cpu_allocatable_number{cluster_name="kubeadmiral-member-2"} 4
kubeadmiral_controller_manager_cluster_cpu_allocatable_number{cluster_name="kubeadmiral-member-3"} 4
kubeadmiral_controller_manager_cluster_cpu_available_number{cluster_name="kubeadmiral-member-1"} 3.0500000000000003
kubeadmiral_controller_manager_cluster_cpu_available_number{cluster_name="kubeadmiral-member-2"} 3.0500000000000003
kubeadmiral_controller_manager_cluster_cpu_available_number{cluster_name="kubeadmiral-member-3"} 3.0500000000000003
kubeadmiral_controller_manager_cluster_memory_allocatable_bytes{cluster_name="kubeadmiral-member-1"} …
```
=> feat: add cluster metrics

pkg/util/informermanager/federatedinformermanager.go, pkg/util/informermanager/informermanager.go
There is a goroutine leak in the implementation of `InformerManager`. This is caused by the `InformerManager`'s handler for `FederatedTypeConfig` is not being unregistered upon stopping.
This results in a goroutine and memory leak as clusters are added and deleted.
Additionally, the `FederatedInformerManager` has also been modified to also unregister its event handler for `FederatedCluster` upon stopping.
=> fix(informer-manager): goroutine leak

pkg/controllers/scheduler/core/generic_scheduler.go, pkg/controllers/scheduler/extensions/webhook/v1alpha1/plugin.go, pkg/controllers/scheduler/extensions/webhook/v1alpha1/plugin_test.go, pkg/controllers/scheduler/framework/plugins/apiresources/apiresources.go, pkg/controllers/scheduler/framework/plugins/apiresources/apiresources_test.go, pkg/controllers/scheduler/framework/plugins/clusterready/clusterready.go, pkg/controllers/scheduler/framework/plugins/placement/filter.go, pkg/controllers/scheduler/framework/runtime/framework.go, pkg/controllers/scheduler/framework/runtime/framework_test.go, pkg/controllers/scheduler/framework/types.go, pkg/controllers/scheduler/scheduler.go
When there is no available clusters, scheduler will result in a `FitError`, and we can get the scheduling details from events.
```
Warning  ScheduleFederatedObject  17m (x4 over 17m)     scheduler                  0/3 clusters are available: 1 cluster(s) didn't match cluster selector, 2 cluster(s) were not in placement list
```
=> feat: add fitError when no available clusters

pkg/controllers/scheduler/framework/plugins/clusterresources/balanced_allocation.go, pkg/controllers/scheduler/framework/plugins/clusterresources/balanced_allocation_test.go, pkg/controllers/scheduler/framework/plugins/clusterresources/fit.go, pkg/controllers/scheduler/framework/plugins/clusterresources/least_allocated.go, pkg/controllers/scheduler/framework/plugins/clusterresources/least_allocated_test.go, pkg/controllers/scheduler/framework/plugins/clusterresources/most_allocated.go, pkg/controllers/scheduler/framework/plugins/clusterresources/most_allocated_test.go, pkg/controllers/scheduler/framework/plugins/rsp/rsp.go, pkg/controllers/scheduler/framework/plugins/rsp/rsp_test.go, pkg/controllers/scheduler/framework/util.go, pkg/controllers/scheduler/schedulingtriggers.go, pkg/controllers/scheduler/schedulingunit.go, pkg/controllers/scheduler/util.go, pkg/util/resource/resource.go
This PR will:
* Pass in the gpu resource request into the scheduling unit
* `ClusterResourceFit` supports filter of gpu
* `MostAllocatable` and `LeastAllocatable` supports gpu resources, and the default weight map will be `cpu: memory: gpu=1:1:4`
* `BalancedAllocatable` supports comparison of GPU resources, based on standard deviation algorithm
=> Support gpu scheduling

pkg/controllers/federate/controller.go, pkg/util/informermanager/federatedinformermanager.go
This fixes incorrect type assertions at various locations that result in the failure to catch when `cache.DeletedFinalStateUnknown` is emitted by the corresponding informer. The subsequent type assertions will then result in a panic.
Example:
=> fix(core): incorrect type assertion to *cache.DeletedFinalStateUnknown

.codecov.yml, .github/workflows/ci.yml, Makefile
Add code coverage detection and ensure that **60%or higher of new code**  is covered with unit tests.
Currently we only focus on the coverage in the `./pkg` directory, and will ignore the following packages or files in this directory:
- "pkg/apis"
- "pkg/client"
- "*_test.go"
- "fake_*.go"
=> ci: integrate the codecov

pkg/apis/core/v1alpha1/extensions_schedulingprofile.go
Disable clusterResourcesFit filter plugin by default because in the scenario which cluster has autoscaler, cluster can scale up nodes to make unschedulable pods running.
=> feat: disable clusterResourcesFit by default

pkg/apis/core/v1alpha1/extensions_schedulingprofile.go, pkg/controllers/scheduler/framework/plugins/clusterterminating/clusterterminating.go, pkg/controllers/scheduler/framework/plugins/clusterterminating/clusterterminating_test.go, pkg/controllers/scheduler/framework/plugins/names/names.go, pkg/controllers/scheduler/profile.go
For the clusters who are in terminating, we can just filter them out directly for the following reasons:
* The sync controller will not dispatch or delete resources from terminating clusters, unless cascading deletion is enabled.
* Considering that the user has submitted the request to delete member clusters, it is expected and more stable to directly filter out when scheduling is triggered.
=> fix(scheduler): add terminating filter

pkg/controllers/scheduler/framework/plugins/rsp/rsp.go, pkg/controllers/scheduler/framework/plugins/rsp/rsp_test.go
When there are three clusters, one do not has gpu resources, the other has gpu resources.
The sum gpu resources of all clusters > 0 but one cluster does not have gpu resources. It will occur a "no gpu resource" error.
=> fix: initialize the total and available amount of GPU resources to 0

pkg/controllers/override/overridepolicy_controller.go, pkg/controllers/override/util.go, pkg/controllers/override/util_test.go
Now we use the following statement to indicate whether overrides are updated.
```
needsUpdate := !equality.Semantic.DeepEqual(overrides, currentOverrides)
```
But overrides's type is `overridesMap`, whereas `currentOverrides` is a slice. So needsUpdate is always true which may lead to some useless updates.
BTW, I discovered that the resource had this event when I created the resource but did not associate the overrides policy which made me feel strange.
```
updated overrides according to override polic(ies)
```
After I deep into the codes, I found this mainly happens when fedobject needs to be updated. It has two situations:
* override policy updates
* pending annotation updates, e.g. we found no ops and removed the override-policy from pending controllers.
In the latter situation, event …
=> fix(overridepolicy-controller): fix using deepEqual incorrectly 

pkg/controllers/federate/controller.go, pkg/controllers/federatedcluster/controller.go, pkg/controllers/sync/controller.go, pkg/controllers/sync/dispatch/unmanaged.go, pkg/controllers/sync/resource.go, pkg/util/finalizers/finalizers.go, pkg/util/finalizers/finalizers_test.go
This PR is to replace runtime.Object with metav1.Object in `pkg/util/finalizers`
related to #99
=> refactor: replace runtime.Object with metav1.Object in pkg/util/finalizers

config/crds/core.kubeadmiral.io_federatedtypeconfigs.yaml, config/sample/host/01-ftc.yaml, pkg/apis/core/v1alpha1/extensions_schedulingprofile.go, pkg/apis/core/v1alpha1/types_federatedtypeconfig.go, pkg/controllers/common/constants.go, pkg/controllers/federate/util.go, pkg/controllers/scheduler/constants.go, pkg/controllers/scheduler/framework/plugins/clusterevicted/cluster_evicted.go, pkg/controllers/scheduler/framework/plugins/clusterevicted/cluster_evicted_test.go, pkg/controllers/scheduler/framework/plugins/names/names.go, pkg/controllers/scheduler/framework/plugins/rsp/rsp.go, pkg/controllers/scheduler/framework/types.go, pkg/controllers/scheduler/planner/planner.go, pkg/controllers/scheduler/planner/planner_test.go, pkg/controllers/scheduler/profile.go, pkg/controllers/scheduler/scheduler.go, pkg/controllers/scheduler/schedulingtriggers.go, pkg/controllers/scheduler/schedulingunit.go, pkg/controllers/scheduler/schedulingunit_test.go, pkg/controllers/scheduler/util.go, pkg/controllers/scheduler/util_test.go, pkg/controllers/statusaggregator/controller.go, pkg/controllers/statusaggregator/plugins/common/migrationconfig.go, pkg/controllers/statusaggregator/plugins/common/migrationconfig_test.go, pkg/controllers/statusaggregator/plugins/plugin.go
To support custom migration we define three types of annotations:
* `kubeadmiral.io/migration-info` on source object: User-entered migration strategy.
* `kubeadmiral.io/latest-migration-info` on source object: The current migration strategy in effect, read-only.
Test Results:
1. WorkloadMigration:
Before migration:
Add migration info anno:
After migration:
SourceObj:
FedObj:
2. ReplicasMigration:
Before migration:
Add migration info anno:
After migration:
SourceObj:
FedObj:
=> feat: support custom migration

pkg/apis/core/v1alpha1/extensions_propagationpolicy.go
replace `pp` with `cpp` as the receiver name of ClusterPropagationPolicy:
1. keep the consistency with other place;
2. avoid the confusion with `pp` of PropagationPolicy.
=> chore: fix receiver naming

pkg/controllers/sync/dispatch/retain.go, pkg/controllers/sync/dispatch/retain_test.go
Some cloud vendors, when creating pods, add resource or dnsConfig configurations through webhooks, causing continuous update failures during deployment. Therefore, when distributing pods, we retain the spec.containers.resources and spec.dnsConfig field.
=> feat: retain pod spec containers resources when sync pod reource

pkg/controllers/sync/dispatch/retain.go
In clusters prior to version 1.24, the default volume name mounted for service accounts is random. 
And pod spec volumes can not been updated, so we retain it.
=> fix: retain pod spec volume when its name has default token prefix

pkg/apis/core/v1alpha1/extensions_federatedobject.go, pkg/controllers/statusaggregator/controller.go, pkg/controllers/sync/controller.go
When deleting derived services in cascade, the deletion cluster gets stuck because the corresponding federatedObj cannot be found.
=> fix: cascading deletion failed when mcs

.github/workflows/dockerhub-latest.yml, .github/workflows/dokcerhub-released.yml, Makefile
=> feat: push images to dockerhub

pkg/controllers/sync/dispatch/managed.go, pkg/controllers/sync/dispatch/retain.go
Now you can use OP to overwrite finalizers like this:
```yaml
spec:
overrideRules:
- overriders:
jsonpatch:
- operator: add
path: /metadata/finalizers/0
value: aaa.bbb.ccc/test
- operator: replace
path: /metadata/finalizers/0
value: aaa.bbb.ccc/new-test
targetClusters:
clusters:
- kubeadmiral-member-2
```
**NOTE:** if you have added new finalizers to member cluster's resources, you have to remove all finalizers before you can delete the resource from the member cluster.
=> fix(override): support overwriting finalizers via OverridePolicy

test/e2e/framework/policies/propagationpolicy.go
In e2e test, fedcorev1a1.PropagationPolicySpec.Placements should be a DesiredPlacement type, not ClusterReference type
*WHAT HAPPEND*
When I run `make e2e` to test official given testcase, the following problem arises：
``` shell
➜  kubeadmiral git:(main) ✗ make e2e                            
ginkgo run -race -tags=e2e  test/e2e -- --kubeconfig=/Users/fangxiaolong/.kube/kubeadmiral/kubeadmiral.config 
Failed to compile e2e:
framework/policies/propagationpolicy.go:41:20: cannot use []fedcorev1a1.ClusterReference{} (value of type []"github.com/kubewharf/kubeadmiral/pkg/apis/core/v1alpha1".ClusterReference) as []"github.com/kubewharf/kubeadmiral/pkg/apis/core/v1alpha1".DesiredPlacement value in struct literal
framework/policies/propagationpolicy.go:46:59: cannot use …
```
=> fix: In e2e test, fedcorev1a1.PropagationPolicySpec.Placements should be a DesiredPlacement type, not ClusterReference type

pkg/controllers/status/controller.go
Why was the collectedStatus object created again after its initial creation? 
I removed this redundant code.
=> fix(status): remove repeat code

pkg/controllers/override/util.go, pkg/controllers/override/util_test.go
see: https://github.com/kubewharf/kubeadmiral/pull/328
=> fix(override): failed to override finalizers

cmd/controller-manager/app/options/options.go, cmd/controller-manager/app/util.go, pkg/controllers/context/context.go, pkg/controllers/federatedcluster/cluster_status_cache.go, pkg/controllers/federatedcluster/clusterstatus.go, pkg/controllers/federatedcluster/controller.go
The cluster status may become abnormal due to a single network jitter.  If this occurs while the application is in the scheduling state, it may lead to the application not being dispatched to that cluster.  Therefore, we have optimized this by adding a detection mechanism for the cluster status to prevent unexpected scheduling results caused by a single network jitter.
=> optimize: add probe for cluster status

.codecov.yml, .github/workflows/ci.yml, pkg/controllers/federatedcluster/clusterstatus.go, pkg/util/cluster/util.go
Remove `reason` tag for cluster_ready_state metrics to clean up residual metrics
=> feat: adjust cluster state metrics

pkg/util/aggregatedlister/global_resource_version.go
String func is also used in a multi-threaded environment, and rlock is required to avoid concurrent map reading and writing.
```
go func(cluster string) {
....
if pod, ok := event.Object.(*corev1.Pod); ok {
clusterobject.MakePodUnique(pod, cluster)
retGrv.Set(cluster, pod.ResourceVersion)
pod.SetResourceVersion(retGrv.String())
event.Object = pod
}
lock.Lock()
if !isProxyChClosed {
proxyCh <- event
}
lock.Unlock()
}
....
}(clusters[i].Name)
```
=> feat：add rlock for string func
