kubewharf/kubeadmiral

- CONTRIBUTING.md
- README.zh.md
Fixed a typo and a broken link in the documentation
> Fix: documentation

- CONTRIBUTING.md
- docs/e2e-tests.md
This adds documentation for running and writing e2e tests.
> Add documentation for e2e tests

- .github/workflows/ci.yml
Example CI run for push to main: https://github.com/gary-lgy/kubeadmiral/actions/runs/4718894465
Example CI run for PR: https://github.com/gary-lgy/kubeadmiral/actions/runs/4718489828
> ci: github actions for testing and linting

- config/crds/core.kubeadmiral.io_clusteroverridepolicies.yaml
- config/crds/core.kubeadmiral.io_overridepolicies.yaml
- pkg/apis/core/v1alpha1/types_overridepolicy.go
- pkg/controllers/sync/resource.go
- allow manual overrides to be applied
- reword override path description
> fix(override): manual overrides are not applied

- pkg/controllers/sync/dispatch/operation.go
atomic.AddInt32 is more prone to alignment issues. Although there are no problems right now with int32 on 32/64 bit systems, it is better to migrate to the new API.
> fix: use atomic.Int32 instead of atomic.AddInt32

- docs/quickstart.md
- hack/dev-up.sh
- hack/util.sh
This PR supports using kwokctl for setting up the dev environment using the dev-up script.
> feat: support kwok in dev-up

- Makefile
- docs/quickstart.md
* enable debug builds with race detection
* enable linting only the changed files from the default branch
* exclude generated files from coverage calculation
* fix corresponding segments in quickstart
> chore(build): improve Makefile

- docs/quickstart.md
> Fixed obsolete kubeconfig path in quickstart.md

- docs/quickstart.md
* comment out dead links
* fix wrong headers
* make the flow from `Installation` to `Managing Kubernetes resources` smoother
* remove the need to create temporary files
> docs: make quickstart clearer

- cmd/controller-manager/app/ftcmanager.go
- pkg/controllers/federate/controller.go
Refactors the federate controller to follow the new logging conventions
> refactor: logging in federate controller

- pkg/controllers/sync/dispatch/retain.go
Read the code comments for caveats.
> feat(retain): support retention of workflows.argoproj.io fields

- pkg/controllers/sync/controller.go
This PR allows cascading delete to handle the case where a resource does not exist in a cluster
> fix: cascading delete handles non-existent resources

- pkg/controllers/federatedcluster/clusterstatus.go
Main contribution:
- collect partial API list for member clusters in case of discovery failure
- filter sub resources
How to test:
1. Create a fake APIService in member cluster 1:
```
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
name: v1alpha1.custom-metrics.metrics.k8s.io
spec:
insecureSkipTLSVerify: true
group: custom-metrics.metrics.k8s.io
groupPriorityMinimum: 1000
versionPriority: 5
service:
name: api
namespace: custom-metrics
version: v1alpha1
```
2. Execute the command in member cluster:
```
kubectl --kubeconfig $HOME/.kube/kubeadmiral/kubeadmiral-member-1.yaml api-resources
```
The output should be:
```
error: unable to retrieve the complete list of server APIs: custom-metrics.metrics.k8s.io/v1alpha1: the server is currently unable to handle the request …
```
> collect partial API list for member clusters in case of discovery failure

- pkg/controllers/common/constants.go
- pkg/controllers/sync/dispatch/managed.go
- pkg/controllers/sync/dispatch/retain.go
- pkg/controllers/sync/resource.go
fix:record labels and annotations after apply overrider to resource
> fix:record labels and annotations after apply overrider to resource

- pkg/controllers/federate/controller.go
> fix: cache mutation in federate controller

- pkg/controllers/federatedcluster/clusterjoin.go
- pkg/controllers/federatedcluster/clusterstatus.go
- pkg/controllers/federatedcluster/controller.go
- pkg/controllers/follower/controller.go
- pkg/controllers/policyrc/controller.go
- pkg/controllers/statusaggregator/controller.go
- pkg/controllers/statusaggregator/plugins/deployment.go
- pkg/controllers/statusaggregator/plugins/plugin.go
- pkg/controllers/statusaggregator/plugins/single_cluster_plugin.go
Refactors the federatedcluster, follower, policyrc, statusaggregator controller to follow the new logging conventions
> refactor: logging in many controller

- pkg/controllers/federatedtypeconfig/federatedtypeconfig_controller.go
- pkg/controllers/status/controller.go
- pkg/controllers/sync/accessor.go
- pkg/controllers/sync/controller.go
- pkg/controllers/sync/dispatch/checkunmanaged.go
- pkg/controllers/sync/dispatch/managed.go
- pkg/controllers/sync/dispatch/operation.go
- pkg/controllers/sync/dispatch/unmanaged.go
- pkg/controllers/sync/history.go
- pkg/controllers/sync/version/manager.go
Refactors the status controller and sync package to follow the new logging conventions
Ref issue #10
> refactor: logging in status controller and sync package

- docs/quickstart.md
fix typo in [quickstart](https://github.com/kubewharf/kubeadmiral/blob/main/docs/quickstart.md)
> chore: fix typo

- pkg/controllers/automigration/controller.go
Fixed reconcile not being re-triggered due to `nextCrossIn` being ignored.
> fix: auto-migration retry after nextCrossIn

- pkg/controllers/federatedcluster/clusterstatus.go
Record the cluster health check body when federated cluster is not ready, so we can analyze the cause of the anomaly.
> chore:add log when federated cluster is not ready

- config/sample/extra/pod-ftc.yaml
- config/sample/host/01-ftc.yaml
- pkg/controllers/automigration/controller.go
- pkg/controllers/automigration/plugins/deployments.go
- pkg/controllers/automigration/plugins/plugins.go
- pkg/controllers/status/controller.go
- pkg/controllers/statusaggregator/controller.go
1. remove revisionHistory of FTC
2. fix failure to get podList in auto-migration
3. fix bug that FTC updating does not trigger status controller
4. ignore resources with NoFederatedResource annotation in statusaggregator
> fix: bugfix for status, statusaggregator and auto-migration

- .github/workflows/ci.yml
- .golangci.yml
- pkg/apis/core/v1alpha1/types_collectedstatus.go
- pkg/controllers/federate/controller.go
- pkg/controllers/nsautoprop/controller.go
- pkg/controllers/scheduler/framework/plugins/apiresources/apiresources.go
- pkg/controllers/scheduler/framework/plugins/apiresources/apiresources_test.go
- pkg/util/collectedstatusadapters/adapter.go
- pkg/util/fedobjectadapters/adapters.go
- pkg/util/informermanager/federatedinformermanager.go
- pkg/util/signals/signal.go
This PR allows the federate controller to adopt orphaned federated objects.
> feat: allow adoption of orphaned federated objects

- pkg/controllers/statusaggregator/plugins/deployment.go
This logic was missed during refactoring.
> fix(status-aggregator): miss clusterObjsUpToDate in deployment

- .gitattributes
https://docs.github.com/en/repositories/working-with-files/managing-files/customizing-how-changed-files-appear-on-github
> chore: mark generated files as linguist-generated

- cmd/controller-manager/app/core.go
- cmd/controller-manager/app/options/options.go
- cmd/controller-manager/app/util.go
- pkg/apis/core/v1alpha1/types_federatedobject.go
- pkg/controllers/context/context.go
- pkg/controllers/sync/controller.go
- pkg/util/orphaning/orphaningannotation.go
This PR is meant to replace https://github.com/kubewharf/kubeadmiral/pull/225
> feat(sync): optimize the cascading deletion of managed member cluster resources

- pkg/controllers/federatedcluster/clusterstatus.go
- pkg/controllers/federatedcluster/controller.go
- pkg/controllers/federatedcluster/util.go
Last transition time should only be updated when there's a transition.
> fix(fcluster): last transition time of cluster conditions

- pkg/controllers/mcs/service_import_controller.go
When repeatedly creating and deleting mcs, and when processing the creation event of mcs, the federatedObject of the originally derived service may still be in the deletion state. Even if the update is successful, the derived service will still be deleted and there will be no chance to retry.
> fix: repeatedly creating and deleting mcs, the creation of derived svc occasionally fails

- go.mod
- go.sum
> feat: upgrade google.golang.org/protobuf to fix cve

- pkg/controllers/override/overridepolicy_controller.go
Fix a bug that the updated ClusterOverridePolicy would not take effect immediately.
> fix(override): enqueue FedObjects using cop

- hack/make-rules/deploy-kubeadmiral.sh
Modify the script to adapt to cn scenes
> fix: Modify the script to adapt to cn scenes

- pkg/controllers/federatedcluster/controller.go
When connecting to a member cluster using a ServiceAccountToken and removing the member cluster, the steps are as follows:
1. Obtain the connection credentials from the ServiceAccountToken secret.
2. Remove the connection credentials from the secret.
3. Remove the finalizers from the fcluster.
In the event of a failure during the third step, when re-entering the queue, the first step retries to obtain the credentials from the secret. However, since the credentials were already deleted in the second step, the attempt to retrieve the credentials fails. Therefore, in this scenario, a retry is added in the third step to address this issue.
> fix: delete cluster failed when failed to remove finalizers

- pkg/controllers/policyrc/controller.go
fix(policyrc): clusterOverridePolicyInformer use persistOpWorker for eventHandler
> fix(policyrc): clusterOverridePolicyInformer add wrong eventHandler 

- pkg/controllers/federatedcluster/cluster_status_cache.go
The member cluster health check will wait for the informer's synchronization. In scenarios where there are many pods and nodes in the member cluster, when the Admiral component restarts, the health check may mark the cluster as not ready because the informer has not finished syncing.
Fix: In such cases, we will retain the cluster state detected before the component restart and use a threshold mechanism to wait for the informer's synchronization to complete.
> fix: member cluster status is not ready when the controller restart
